# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  #welcome: circleci/welcome-orb@0.4.1
  katalon-studio: katalon/katalon-studio@23.0.11
  barath-orb:
    executors:
      default:
        docker:
          - image: circleci/ruby:1.4.2
    commands:
      browser:
        steps:
          - run: echo $BROWSER
    jobs:
      katalonjob:
        executor: default
        steps:
          - browser
          



# Orchestrate or schedule a set of jobs

           
workflows:
  #build:
  sample-workflow:
    jobs:
      - barath-orb/katalonjob
      - katalon-studio/run:
          version: latest
          command_arguments:  -retry=0 -testSuitePath="Test Suites/Verify Operations" -executionProfile="default" -browserType="Chrome" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true
   #jobs:
    #  - katalon-studio/run:
    #      version: latest
    #      command_arguments:  -retry=0 -testSuitePath="Test Suites/Verify Operations" -executionProfile="default" -browserType="Chrome" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true
#  healthcheck:
#    triggers:
#      - schedule:
#          cron: "5 * * * *"
#          filters:
#            branches:
#              only:
#                - main
#    jobs:
#      - katalon-studio/run:
#          version: latest
#          command_arguments:  -retry=0 -testSuitePath="Test Suites/Verify Operations" -executionProfile="default" -browserType="Chrome" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true